vim.cmd [[let g:vim_current_word#highlight_twins = 1]]
vim.cmd [[let g:vim_current_word#highlight_current_word = 1]]
vim.cmd [[let g:vim_current_word#highlight_delay = 0]]
vim.cmd [[let g:vim_current_word#highlight_only_in_focused_window = 1]]
vim.cmd [[let g:vim_current_word#enabled = 1]]
